### ISSUE TITLE
Signature format

### ISSUE THREAD

**Issue by mathiasrw** [BitcoinFiles/AUTHOR_IDENTITY_PROTOCOL#1]
AWESOME initiative. 

----

In the example its a 130 char hex value. Is it correctly understood that it will always be a 512 bit output from the signiture = 128 hex chars?

> Signature: The signature of the signed content with the Signing Address. Base64 encoding.

Also, Is it ment to be base64 encoded in the transaction?

**Comment by attilaaf** [comment]
Thanks!

The encoding is actually hex in the OP_RETURN. That's a typo -- I'll correct it.

We pull out the hex data of the signature in the OP_RETURN then `toString('base64')` because that's what `bsv.js` expects:
https://github.com/BitcoinFiles/bitcoinfiles-sdk/blob/master/lib/utils.ts#L201

You can see how the signature is being used here with `bsv.js`:
Then verified here: https://github.com/BitcoinFiles/bitcoinfiles-sdk/blob/master/lib/utils.ts#L243

To recap:

op_return data stores signature as raw bytes (hex encoded).  But when we pull out the data we do `toString('base64')` because that's what `bsv.js` expects.

>In the example its a 130 char hex value. Is it correctly understood that it will always be a 512 bit output from the signature = 128 hex chars?

This is <Signing Algorithm> defined. There's no reason you could not use PGP or any other system. By default we use "BITOIN_ECDSA".  

Therefore, there is no definition for how long the <Signature> field is.  We can imagine BITCOIN_ECDSA_v2 which uses 4096 bits (or whatever).

I hope this answers it!

**Comment by mathiasrw** [comment]
Makes sense with the base64 - but might need some words to explain it for others. 

So is the 130 chars in the example is an error? It should have been 128 right? or is there an extra control byt (2 hex chars)

**Comment by attilaaf** [comment]
Maybe it is a bad example. I'll check and update the docs soon.

In the mean time here is a live good example:

https://github.com/BitcoinFiles/bitcoinfiles-sdk/blob/master/test/build.js#L36
