### ISSUE TITLE
`OP_FALSE OP_RETURN` Support 

### ISSUE THREAD

**Issue by ryejoon** [BitcoinFiles/AUTHOR_IDENTITY_PROTOCOL#2]
From `README.md`, it says
`NOTE: THE LIBRARY ASSUMES THAT THE 0'th INDEX IS THE OP_RETURN(0x6a).`
Any plan to support `OP_FALSE OP_RETURN`?

**Comment by rohenaz** [comment]
I don't think so :(
The problem is, if signed data starts at OP_FALSE it would be a conflict for all the existing on-chain signatures. If we stay consistent that signatures begin with OP_RETURN there is no breaking change, and I can't think of a negative consequence for this other than feeling like OP_FALSE was left out, but being that this is an "OP_RETURN protocol" you can make the case it still fits logically.
